In [2]:
import numpy as np

# Basics

In [3]:
a = np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# get the number dimentsions of an numpy array
a.ndim
b.ndim

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get Type
a.dtype


dtype('int16')

In [7]:
# get the size : gives the size in byte (B)
a.itemsize

2

In [12]:
# get the total size
a.size * a.itemsize
# or 
a.nbytes

b.nbytes

48

# Accessing or Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# get a specific element [ row, column ]
a[1, -7]

8

In [18]:
 # getting a specific row
a[0, :] 

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# getting a specific colunmn
a[:, 0]

array([1, 8])

In [22]:
# more specific than just rows and columns [start_index:end_index:step_size]
a[0, 1:6:2]
a[0, 0: -1:3]

array([1, 4])

In [27]:
# changing the value of a element\
a[1,2] = 999
print(a)
a[:, 2] = [78, 74]
print(a)

[[  1   2  78   4   5   6   7]
 [  8   9 999  11  12  13  14]]
[[ 1  2 78  4  5  6  7]
 [ 8  9 74 11 12 13 14]]


In [30]:
# example of 3-d array
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

# selecting in 3-d
b[1,1,0]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


7

In [32]:
# replace
b[:,1,:] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of Arrays

In [34]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
# All 1s matrix
np.ones((5,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [39]:
  # Any other number
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [47]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
## Random decimal numbers
np.random.rand(5,6,7)

array([[[0.147115  , 0.99165819, 0.06585885, 0.30214467, 0.70480858,
         0.63234089, 0.75606537],
        [0.60497038, 0.49550014, 0.25372913, 0.49814831, 0.45013022,
         0.51698193, 0.02029312],
        [0.22133907, 0.18113561, 0.54958074, 0.81885567, 0.63203814,
         0.77219986, 0.33548161],
        [0.66287855, 0.85326784, 0.3868515 , 0.26588917, 0.90071086,
         0.49949854, 0.74113683],
        [0.98360681, 0.53798709, 0.77702528, 0.23949922, 0.15756003,
         0.93079916, 0.94515908],
        [0.30809989, 0.69103357, 0.83409146, 0.58581823, 0.93752814,
         0.42456103, 0.28492874]],

       [[0.08196617, 0.20095723, 0.4566205 , 0.06080352, 0.70543381,
         0.42538991, 0.17628032],
        [0.40684131, 0.21541159, 0.85688301, 0.95490024, 0.89743106,
         0.96242733, 0.63040321],
        [0.18432535, 0.42646543, 0.03036446, 0.66723383, 0.85552312,
         0.55887692, 0.84644477],
        [0.36390828, 0.54703702, 0.95317245, 0.72509352, 0.19362235,
  

In [51]:
# For using the shape
np.random.random_sample(a.shape)

array([[0.30749861, 0.6906046 , 0.7169572 , 0.96420588, 0.7438034 ,
        0.93571111, 0.08672054],
       [0.3080442 , 0.89571251, 0.37510827, 0.55930909, 0.82583835,
        0.08157465, 0.3644115 ]])

In [54]:
#random integer values
np.random.randint(7, size=(3,3))

array([[1, 0, 4],
       [1, 0, 0],
       [3, 2, 0]])

In [55]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
# repeat the array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [74]:
output = np.ones((5,5))
output

sub = np.zeros((3,3))
sub
sub[1,1] = 9
sub

output[1:4, 1:4] = sub
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!!!

In [78]:
a = np.array([1,2,3])
b = a  # b get a reference to the a, b doesn't store a copy of a in this case
print(b)
b[1] = 1000
print(a)

[1 2 3]
[   1 1000    3]


In [79]:
# for copying
a = np.array([3,4,6])
b = a.copy()
b[0] = 99
print(a)

[3 4 6]


# Mathematics

In [82]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [83]:
a + 2

array([3, 4, 5, 6])

In [84]:
a - 2

array([-1,  0,  1,  2])

In [85]:
a * 3

array([ 3,  6,  9, 12])

In [86]:
a / 4

array([0.25, 0.5 , 0.75, 1.  ])

In [88]:
b = np.array([1, 0, 1, 0])

In [89]:
a + b

array([2, 2, 4, 4])

In [90]:
a ** 2

array([ 1,  4,  9, 16])

In [93]:
# sin value of all the elements of a
np.sin(a)
np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

## Linear Algebra

In [94]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [96]:
# Find the det of the matrix
matrix_x =  np.identity(3)
np.linalg.det(matrix_x)

1.0

# Statistics

In [97]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.min(stats, axis=1) #axis = 1 : row wise minimum

array([1, 4])

In [99]:
np.max(stats) # axis = 0: column wise maximum    

6

# Reorganizing Arrays

In [101]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [102]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

##### Load Data from file to numpy array

In [111]:
file_data = np.genfromtxt('data.txt', delimiter=",")
file_data = file_data.astype('int16')
file_data

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]], dtype=int16)

# Boolean masking and Advanced Indexing

In [107]:
file_data > 3   # boolean return : can use any comparison symbol

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [108]:
file_data[file_data > 4]

array([5, 5, 6, 7, 8], dtype=int16)

In [112]:
# Index can be done with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [113]:
np.any(file_data > 4, axis=0) # check each column and let us know which column has a value gt 4

array([False,  True,  True,  True,  True])

In [114]:
np.all(file_data > 4, axis=0)  # check each column and let us know if all values of a column is gt 4

array([False, False, False, False,  True])

In [118]:
~((file_data > 2) & (file_data < 5))

array([[ True,  True, False, False,  True],
       [False,  True,  True,  True,  True]])